services:
  shortenerDB:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: shortenerDB
    ports:
    - "5432:5432"
    volumes:
    - data:/var/lib/postgresql

volumes:
  data:
